# server.R
# Author: T Houwers
# Date: 24-11-2021
# Description: Shiny UI, Coursera Data Science Capstone Final Project Assignment

# load the n-grams generated by previous assignment
bigram <- readRDS("./data/bigram.RData")
trigram <- readRDS("./data/trigram.RData")
start_words <- c("you","are","awesome")

# Predict the next words
data_prediction <- function(input_user, ngrams) {

    # trigram
    if (ngrams >= 3) {
        input_user1 <- paste(input_user[length(input_user)-1], input_user[length(input_user)])
        dataTokens <- trigram %>% filter(variable == input_user1)
        if (nrow(dataTokens) >= 1) {
            return(dataTokens$outcome[1:3])
        }
        # backoff to bigram
        return(data_prediction(input_user, ngrams - 1))
    }

    # bigram (and lower)
    if (ngrams < 3) {
        input_user1 <- input_user[length(input_user)]
        dataTokens <- bigram %>% filter(variable == input_user1)
        ##dataTokens <- bigram %>% filter(token == input_user1)
        return(dataTokens$outcome[1:3])
    }
    # unigram: not implemented to enhance performance
    return(NA)
}

clean_words <- function(input) {
    if (input == "" | is.na(input)) {
        return("")
    }

    input <- tolower(input)

    # remove URL, email addresses, Twitter handles and hash tags
    input <- gsub("(f|ht)tp(s?)://(.*)[.][a-z]+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("\\S+[@]\\S+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("@[^\\s]+", "", input, ignore.case = FALSE, perl = TRUE)
    input <- gsub("#[^\\s]+", "", input, ignore.case = FALSE, perl = TRUE)

    # remove ordinal numbers
    input <- gsub("[0-9](?:st|nd|rd|th)", "", input, ignore.case = FALSE, perl = TRUE)

    # remove punctuation
    input <- gsub("[^\\p{L}'\\s]+", "", input, ignore.case = FALSE, perl = TRUE)

    # remove punctuation (leaving ')
    input <- gsub("[.\\-!]", " ", input, ignore.case = FALSE, perl = TRUE)

    # trim leading and trailing whitespace
    input <- gsub("^\\s+|\\s+$", "", input)
    input <- stripWhitespace(input)

    if (input == "" | is.na(input)) {
        return("")
    }

    input <- unlist(strsplit(input, " "))

    return(input)

}

predict_words <- function(input, word = 0) {

    input <- clean_words(input)

    if (input[1] == "") {
        output <- start_words
    } else if (length(input) == 1) {
        output <- data_prediction(input, ngrams = 2)
    } else if (length(input) == 2) {
        output <- data_prediction(input, ngrams = 3)
    } else if (length(input) > 2) {
        output <- data_prediction(input, ngrams = 4)
    }

    if (word == 0) {
        return(output)
    } else if (word == 1) {
        return(output[1])
    } else if (word == 2) {
        return(output[2])
    } else if (word == 3) {
        return(output[3])
    }

}

shinyServer(function(input, output) {

    # original sentence
    output$user_input <- renderText({input$input_user});

    # reactive controls
    observe({
        pred_num <- input$pred_num
        if (pred_num == 1) {
            output$pred1 <- reactive({predict_words(input$input_user, 1)})
            output$pred2 <- NULL
            output$pred3 <- NULL
        } else if (pred_num == 2) {
            output$pred1 <- reactive({predict_words(input$input_user, 1)})
            output$pred2 <- reactive({predict_words(input$input_user, 2)})
            output$pred3 <- NULL
        } else if (pred_num == 3) {
            output$pred1 <- reactive({predict_words(input$input_user, 1)})
            output$pred2 <- reactive({predict_words(input$input_user, 2)})
            output$pred3 <- reactive({predict_words(input$input_user, 3)})
        }
    })

})
